### ISSUE TITLE
Add Code of Conduct 

### ISSUE THREAD

**Issue by Princegupta101** [gofr-dev/website#43] opened 2024-05-10 08:49 UTC
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by suhanipaliwal** [comment] 2024-05-10 16:40
I would like to work on this issue. Please assign me this task.

**Comment by Ambika03p** [comment] 2024-05-11 04:07
Currently, the repository lacks a Code of Conduct file, which is an essential component for fostering a healthy and inclusive open-source community. A Code of Conduct serves as a guideline for expected behavior, ensuring that contributors and participants feel safe, respected, and valued within our community space.

Kindly assign me this issue, so i can work towards it under GSSOC 24

**Comment by officeneerajsaini** [comment] 2024-05-13 14:08
@gofr-dev , I'd like to work on this issue under GSSOC. Could you please add the necessary label and tag to the issue and assign it to me?

**Comment by n14rishitha** [comment] 2024-05-18 05:39
Hi @gofr-dev
the code of conduct takes effect (on issues and pull requests, or community activities like events?). Adopting, and enforcing, a code of conduct can help create a positive social atmosphere for your community. 
I would like to work on this issue . so please assign this task to me under the label gssoc24 and level1,2,or 3

**Comment by srijan-27** [comment] 2024-06-25 06:09
Duplicate of #38

**Closed by srijan-27** 2024-06-25 06:09 UTC
Labels: duplicate
